M48
; DRILL file {KiCad 6.0.11+dfsg-1~bpo11+1} date Thu Apr 13 11:16:25 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-13T11:16:25+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1~bpo11+1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.889
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C3.000
%
G90
G05
T1
X5.54Y-16.12
X18.29Y-8.17
T2
X-0.81Y-5.95
X-0.81Y-8.49
T3
X0.0Y0.0
X0.0Y-20.32
X40.64Y0.0
X40.64Y-20.32
T0
M30
