M48
; DRILL file {KiCad 6.0.11+dfsg-1~bpo11+1} date Thu May 25 08:20:36 2023
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2023-05-25T08:20:36+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1~bpo11+1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.889
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C3.000
%
G90
G05
T1
X5540Y-16120
X18290Y-8170
T2
X-810Y-5950
X-810Y-8490
T3
X0Y0
X0Y-20320
X40640Y0
X40640Y-20320
T0
M30
