M48
; DRILL file {KiCad 7.0.5.1-1-g8f565ef7f0-dirty-deb11} date Wed Jul  5 15:12:21 2023
; FORMAT={3:3/ absolute / metric / suppress leading zeros}
; #@! TF.CreationDate,2023-07-05T15:12:21+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5.1-1-g8f565ef7f0-dirty-deb11
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.889
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C3.000
%
G90
G05
T1
X5540Y-16120
X18290Y-8170
T2
X-810Y-5950
X-810Y-8490
T3
X0Y0
X0Y-20320
X40640Y0
X40640Y-20320
T0
M30
